### ISSUE TITLE
Fix Sandbox launch for HSPC Sandboxes who don't have default patient set data

### ISSUE THREAD

**Issue by zplata** [cds-hooks/legacy-sandbox#103]
The patient pick list of default patients still appear for HSPC FHIR servers who don't have the starter default patient data configured. This should not be an option any more as those patients could lead to a 404 on trying to load the patient resource.

Overall, the Sandbox needs to be flexible with the HSPC FHIR server in context, and not assume the user created the HSPC FHIR server with the default data in place.

**Comment by kpshek** [comment]
Closing out graveyard issues on the deprecated legacy Sandbox. If this issue is still desired, please log an issue against our new [sandbox](https://github.com/cds-hooks/sandbox/issues).
