### ISSUE TITLE
Consider integrating cds-validator project for message validation

### ISSUE THREAD

**Issue by mattberther** [cds-hooks/legacy-sandbox#104]
Recently, https://github.com/cds-hooks/cds-validator was brought up-to-date with the current draft of the CDS Hooks 1.0 specification. It may make sense to leverage this project in the sandbox to validate CDS payloads as they come in to make sure they conform to the schema.

The 1.0 rc package is available via npm install cds-validator@1.0.0-rc.1. I'm planning on keeping it on the same version as the CDS spec, so once we see a final on the spec, I'll release the 1.0.0 package.

If any issues come up during integration, please log an issue at the cds-validator project.

**Comment by kpshek** [comment]
Closing out graveyard issues on the deprecated legacy Sandbox. If this issue is still desired, please log an issue against our new [sandbox](https://github.com/cds-hooks/sandbox/issues).
