### ISSUE TITLE
help: card `actions` for delete operation do not execute requested actions

### ISSUE THREAD

**Issue by cdaringe** [cds-hooks/legacy-sandbox#109]
# problem statement

when sending an action suggestion bound to _deleting_ a FHIR resource, on click of the resultant card button, the FHIR resource is not deleted.  we are wiring in the stu3 FHIR server here: `https://sb-fhir-stu3.smarthealthit.org/smartstu3/open`

```js
{
  label: 'Cancel Screen',
  uuid: 123,
  actions: [
    {
      type: 'delete',
      description: 'Cancel Screen',
      resource: 'ProcedureRequest/152763'
    }
  ]
}
```

# discussion

per viewing the sources, it's not immediately clear that these are handled in the sandbox.  can you confirm?

**Comment by kpshek** [comment]
Closing out graveyard issues on the deprecated legacy Sandbox. If this issue is still desired, please log an issue against our new [sandbox](https://github.com/cds-hooks/sandbox/issues).
