### ISSUE TITLE
Update FHIR server

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/legacy-sandbox#13]
A developer reached out to me with:

> The default FHIR server used by the http://demo.cds-hooks.org/ app should be changed to newer version of FHIR. Currently, it is pointing to http://hooks.smarthealthit.org:9080/  which uses DSTU2 ballot version of value set for Condition.CinicalStatus:
[provisional | working | confirmed | refuted | entered-in-error | unknown]
instead of [active | relapse | remission | resolved]

**Comment by jmandel** [comment]
Is the comment saying that we shouldn't be using DSTU2, or that we're not
using the final published DSTU2 specification?

**Comment by kpshek** [comment]
That we're not using the final published DSTU2 I think

**Comment by jmandel** [comment]
Indeed -- that's an error in SMART's sample data (and also an erorr in the DSTU2 spec, which lists this binding as `preferred` instead of `required`).

**Comment by kpshek** [comment]
This will be addressed in #49. Closing.
