### ISSUE TITLE
Rename app to CDS Hooks Sandbox

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/legacy-sandbox#16]
Currently, we're using demo.cds-hooks.org and "CDS Hooks Demo". While this is a demo, we always just refer to this as the "CDS Hooks Sandbox" or "CDS Hooks Test Harness". While this app can be used for a demo, sandbox is a more appropriate name. Additionally, the concept of a sandbox is well understood in both the SMART and FHIR communication.

Acceptance criteria:
- Rename the site to "CDS Hooks Sandbox"
- Redeploy to sandbox.cds-hooks.org

After this change is made I think it would be good to rename the repository to `cds-hooks-sandbox`

**Comment by kpshek** [comment]
@zplata will be working on this issue

**Comment by jmandel** [comment]
Great! We might just call the new repo "sandbox" on the basis that it lives in the cds-hooks org (there are pros/cons here, but it's nice for us to retain this kind of organizational context).

**Comment by kpshek** [comment]
👍  to just naming the repo "sandbox"

**Comment by kpshek** [comment]
fyi: I've merged `v-swagger` to `master`, deleted the `v-swagger` branch, and renamed the repository to `sandbox`.
