### ISSUE TITLE
Add the ability for developers to hook up an arbitrary hook

### ISSUE THREAD

**Issue by zplata** [cds-hooks/legacy-sandbox#26]
Currently the CDS Hooks Sandbox tool allows developers to interact with the `medication-prescribe` and `patient-view` hook views. As [more and more hooks](https://github.com/cds-hooks/docs/wiki/Proposed-Hooks) are being proposed, it also might make sense for developers to configure an arbitrary hook (i.e, `my-custom-hook`). 

There probably needs to be more discussion around the implementation of this feature, as generalizing this idea might be tricky.

Acceptance criteria:
- Provide a way for developers to add arbitrary hooks

**Comment by kpshek** [comment]
Closing out graveyard issues on the deprecated legacy Sandbox. If this issue is still desired, please log an issue against our new [sandbox](https://github.com/cds-hooks/sandbox/issues).
