### ISSUE TITLE
Should include a clinical scenario for the built-in patient-view and medication-review hooks

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/legacy-sandbox#39]
Reposting the issue @manojhajur logged in cds-hooks/docs#54:

> Can we include a relevant clinical scenario in the documentation, such that those who are reviewing the Introduction wiki page, or the sandbox demo page (a doc link on the top right of each main page for that hook), then they can see the use of the cds-hooks spec?
>
>ie.
>
>1. select Rx Review
>2. select patient X
>3. select problem Y
>4. select med Z
>5. review "cards" and select med Z3
>6. see final decision

**Comment by vadi2** [comment]
@manojhajur happy to work on an example for this. Can you procure clinically-relevant sample data to create the example from?

**Comment by kpshek** [comment]
Closing out graveyard issues on the deprecated legacy Sandbox. If this issue is still desired, please log an issue against our new [sandbox](https://github.com/cds-hooks/sandbox/issues).
