### ISSUE TITLE
Ideas for stub services

### ISSUE THREAD

**Issue by jmandel** [cds-hooks/legacy-sandbox#6]
1. "Prior auth" before an Rx is written (e.g. for HepC rx)
2. Pediatric dose assessment/adjustment
3. Drug/drug interaction, or Drug/allergy
4. Domain-specific Rx tool (e.g. HTN, Diabetes) that runs outside of the EHR and returns a completed Rx

**Comment by kpshek** [comment]
Closing out graveyard issues on the deprecated legacy Sandbox. If this issue is still desired, please log an issue against our new [sandbox](https://github.com/cds-hooks/sandbox/issues).
