### ISSUE TITLE
URL encode prefetch

### ISSUE THREAD

**Issue by yashaskram** [cds-hooks/legacy-sandbox#64]
Observation prefetch below fails because it is not url encoded when using the app with https://sb-fhir-dstu2.smarthealthit.org/api/smartdstu2/open fhir server

"hook": "patient-view",
      "prefetch": {
        "patient": "Patient/{{Patient.id}}",
        "condition": "Condition?patient={{Patient.id}}",
        "observation": "Observation?patient={{Patient.id}}&category=laboratory&code=http://loinc.org|2857-1,http://loinc.org|35741-8"

Is CDS vendor expected to handle this by providing url encoded prefetch queries like below or EHR should handle this?

"Observation?patient=SMART-967332&category=laboratory&code=http://loinc.org%7C2857-1"

**Comment by anoush-bch** [comment]
I also ran into problems using not encoded loinc code in my prefetch to https://sb-fhir-stu3.smarthealthit.org/smartstu3/open, encoding the loinc code solved it:
encodeURI('http://loinc.org|')

**Comment by kpshek** [comment]
@zplata - Can you take a look at this please?

**Comment by zplata** [comment]
Sure, we can encode the url query parameters on the Sandbox end. We'll start work on this now.
