### ISSUE TITLE
Provide guidance on mixed content scenario

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/legacy-sandbox#71]
We've recently enabled TLS for cds-hooks.org which includes the Sandbox. So, developers can now access the Sandbox over at a TLS protected endpoint at https://sandbox.cds-hooks.org.

If a developer accesses the secure version of our Sandbox, they will get [mixed content](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content) warnings in the browser if their CDS Service is only available over a http endpoint. We should update the Sandbox to notify the developer of this scenario and help them mitigate it (tell the browser to accept mixed content) or point them to a service like [Let's Encrypt](https://letsencrypt.org/) to get a free SSL certificate.

We can provide this guidance in two spots:

- When the developer tries to add a new Discovery endpoint
- Anytime an http CDS Service is configured already

The guidance could be a banner that is displayed, perhaps in the header somewhere. Though, I'm open to other thoughts/ideas.

**Comment by jmandel** [comment]
We can also think about catching these errors when they occur and bubbling them up to the UI.

**Comment by kpshek** [comment]
Closing out graveyard issues on the deprecated legacy Sandbox. If this issue is still desired, please log an issue against our new [sandbox](https://github.com/cds-hooks/sandbox/issues).
