### ISSUE TITLE
Support SMART app launches against any arbitrary secured FHIR server

### ISSUE THREAD

**Issue by zplata** [cds-hooks/legacy-sandbox#73]
Currently, there is work to support SMART app launches against any FHIR server created from an HSPC sandbox instance. This works by hitting the endpoint of `{base-iss-server}/_services/smart/Launch}`. In the Sandbox, the path to this endpoint is hard-coded for now. More details and discussion in this pull request [here](https://github.com/cerner/cds-hooks-sandbox/pull/32). 

For this concept of launching against the secured FHIR server to be further supported, we need to have the Sandbox discover this specific launch context API somehow, instead of assuming the endpoint exists at the FHIR server. This would allow vendors who implement this API to define how to reach this endpoint at an implementation level, while still exposing it in the same manner as any other vendor. This more specifically helps vendors who want to implement the endpoint at a location other than the FHIR server, but still want to expose it in a standard place.

In the pull request mentioned above, we could propose to have this launch context endpoint discovered in the conformance/capability statement of the FHIR server the Sandbox is launched against, under the `rest.extension` property. Open to discussion and thoughts here!

**Comment by kpshek** [comment]
Closing out graveyard issues on the deprecated legacy Sandbox. If this issue is still desired, please log an issue against our new [sandbox](https://github.com/cds-hooks/sandbox/issues).
