### ISSUE TITLE
Return from external service UI isn't working

### ISSUE THREAD

**Issue by jmandel** [cds-hooks/legacy-sandbox#75]
e.g. when an external app redirects to http//sanbox.cds-hooks.org/service-done.html, nothing happens.

**Comment by jmandel** [comment]
Steps to reproduce: 

1. Visit http://sandbox.cds-hooks.org
2. Add CDS Service `http://hooks.fhir.me:8082/cds-services`
3. Choose Rx View
4. Choose from problems: "Benign Essential Hypertension"
5. In the resulting card, click "Tailor therapy with JNC Pro"
6. In the external tool, click "Thiazide"

At this point, http://sandbox.cds-hooks.org/service-done.html loads but does not close itself or successfully communicate back with the sandbox tab -- so the user flow gets stuck.

**Comment by zplata** [comment]
Hey @jmandel, taking a look at this now. I think the redirect to the Sandbox with the Sandbox closing the `/service-done.html` can be fixed. My concern is with supporting the existing decision support flow for which this decision-centric CDS Service was probably meant for. 

For context, we [recently fixed a bug](https://github.com/cds-hooks/sandbox/commit/33a41f8535c1274fab68b5a6b3039139a7bae8f9) where the CDS Hooks Sandbox was using one UUID in the `hookInstance` for all CDS Service calls in a particular session. Before this fix, what happened was when the "Tailor Therapy App" returned flow back to the EHR, the CDS Services would be re-invoked using the exact same `hookInstance` in the initial call, thus allowing the `pediatric-dose-check` service to return an eventual decision the way the logic is setup for that service. 

Currently in the `pediatric-dose-check` service, when it returns flow back to the EHR, no data is really passed in, making it hard to see which CDS Service to re-invoke, specifically without the initial `hookInstance`. Do you have any suggestions for whether this will require a change in the `pediatric` CDS service to send data to the redirect URL, and for the redirect to `postMessage` that data back to the EHR, or possibly some change on the Sandbox side?

**Comment by zplata** [comment]
From an offline discussion with @jmandel, the EHR should be able to construct a unique redirect URL for each request that can easily trace the `hook-instance` UUID back to itself if a decision flow returns back to the EHR. In this case, the EHR has the responsibility to restore the session.

For the Sandbox, we can add a fragment identifier with the UUID of the request to the service (i.e. `http://sandbox.cds-hooks.org/service-done.html#{hook-instance-uuid}`). This redirect page can postMessage that UUID back to the EHR and the EHR can in turn invoke the UUID to successfully execute the rest of the decision flow.
