### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by jasonfmo** [cds-hooks/legacy-sandbox#8]
Any chance of a readme with build instructions/environment setup?

**Comment by jmandel** [comment]
That would be a very good todo. @jasonfmo, would having a ready-to-go Docker instance be useful for you on this?

**Comment by jasonfmo** [comment]
yep @jmandel, that could work too.

**Comment by jmandel** [comment]
I've added a quick guide to getting a local dev environment set up (using docker, docker-compose) in https://github.com/jmandel/cds-hooks-rx-app/blob/master/README.md

The simpler story if you're just looking to do local dev is:

### Setup

```
npm install -g nodemon
git clone https://github.com/jmandel/cds-hooks-rx-app
cd cds-hooks-rx-app
npm install
cd mock-cds-backend
npm install
```

### Run it in dev

```
cd cds-hooks-rx-app 
npm run-script dev
```

```
cd cds-hooks-rx-app/mock-cds-backend
nodemon index.js
```
