### ISSUE TITLE
JWT errors in calls to CDS Services

### ISSUE THREAD

**Issue by zplata** [cds-hooks/legacy-sandbox#82]
There are a few issues with the current JWT being sent in the Sandbox, and calls not containing the JWT.

1) Now that the Sandbox has support for `https`, we should flex the `iss` parameter of the JWT to match the protocol the Sandbox uses.
2) There are two calls being made to the discovery endpoint once a CDS Service discovery is added to a Sandbox. One is a call to verify that the discovery endpoint is reachable (no JWT included), and another to actually grab and store the service definitions from the discovery endpoint. The second call to the endpoint actually contains the JWT, so CDS service providers may notice a first call without a JWT, and thus seems inconsistent with the spec.
3) The `aud` parameter of JWTs in service requests lately have a URL value of the first CDS service configured in the sandbox for all JWTs (i.e. `hooks.fhir.me:8082/cds-services/patient-hello-world`). This is a bug, where the `aud` parameter needs to be the cds service endpoint URL.

**Comment by nlush** [comment]
Hi Zach,
Do you know if this open issue will be fixed prior to the Connectathon?  
If possible, we would like to see a card for each service, when multiple services are offered.
Also, there is a new service drop down.  Is that intended to refresh to the selected service?  Currently there is no mechanism to switch to a different service.
Thanks, Nancy

**Comment by zplata** [comment]
@nlush - We will be able to get this fixed this week prior to the Connectathon, it's out on a pull request right now [here](https://github.com/cds-hooks/sandbox/pull/83), sorry for the delay on this. Once these JWT issues are pulled in and deployed on this project, your services should be able to display their cards respectively. On Cerner's side, we tested these JWT fixes on our fork of this project, and you can test out your services on our tested deployment here: http://engineering.cerner.com/cds-hooks-sandbox.

I'm not sure what new service dropdown was added. Do you mind posting a screenshot here for clarification? Once a discovery endpoint is added (successfully), and the new CDS Services are pulled in, the cards should show right away on the left hand side, but you may need to use the select dropdown box to click on the new CDS service you want to see the request/response for on the toggle panels.  Sometimes, it may take a few seconds for the new cards to show up depending on how fast the CDS service exchange takes.

**Comment by nlush** [comment]
Thanks Zach.  Everything looks great on the Cerner sandbox.  

Unfortunately I can't get a representative screen shot since the drop down select disappears when it looses focus.  I was referring to the service toggle.  On the sandbox at http://sandbox.cds-hooks.org that drop down does not function.  If I select a different service, it does not change the service - independent of any time delay.  It works fine on the Cerner sandbox.
Thx
