### ISSUE TITLE
Fix Content-types

### ISSUE THREAD

**Issue by jmandel** [cds-hooks/legacy-sandbox#9]
From e-mail report

>  Another thing I noticed is that we were receiving from the cds hooks program:
> Content-Type:application/json;charset=UTF-8
> Also we are receiving:
> Accept:application/json, text/plain, _/_
> I read the fhir specs suggest other values and to use the _format query parameter if it is not possible to set the accept type through the client library.
> https://www.hl7.org/fhir/http.html
> I've worked around these but I'm not sure if I should according to the spec.

We should indeed fix these in the demo app!

**Comment by kpshek** [comment]
Closing out graveyard issues on the deprecated legacy Sandbox. If this issue is still desired, please log an issue against our new [sandbox](https://github.com/cds-hooks/sandbox/issues).
