### ISSUE TITLE
JWT token does not have contain the 'sub' field in the payload

### ISSUE THREAD

**Issue by olbrich** [cds-hooks/legacy-sandbox#92]
https://cds-hooks.org/specification/1.0/#trusting-ehrs

Specifies the following fields to be required in the payload: 

`iss`,`sub`, `aud`,`exp`,`iat`,`jti`

But only 

`iss`, `aud`, `exp`, `iat`, and `jti` are currently in the JWT generated by the sandbox.

Leaving `sub` to be implemented.

**Comment by kpshek** [comment]
Closing out graveyard issues on the deprecated legacy Sandbox. If this issue is still desired, please log an issue against our new [sandbox](https://github.com/cds-hooks/sandbox/issues).
