### ISSUE TITLE
Document location of public key for JWT tokens

### ISSUE THREAD

**Issue by olbrich** [cds-hooks/legacy-sandbox#93]
At times it is helpful to use the sandbox to interact with cds-services running on localhost, however, the public key used to sign the JWT token will be required to work properly.

**Comment by kpshek** [comment]
@olbrich - The Sandbox public key is here: https://github.com/cds-hooks/sandbox/blob/master/ecpublickey.pem

**Comment by olbrich** [comment]
now it's at http://sandbox.cds-hooks.org/.well-known/jwks.json
