### ISSUE TITLE
Add experimental error indicator for CDS Services that want to return error cards

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/legacy-sandbox#94]
At the NOLA Connectathon meeting (Friday, 1/26 4-6p), we discussed cds-hooks/docs#14. A major focus of this discussion was how a CDS Service could communicate an error back to the end user (clinician). We discussed experimenting at the Connectathon with a new card `indicator` value of `error`.

This new indicator should result in the card styling separate than our other indicators. Perhaps a red border?

**Comment by zplata** [comment]
Red is currently being used for `hard-stop`. Maybe we should use black for error? Or vice versa
